#  ................................................................................................................................
# .................................................................................................................................
#....lMi.......M#..........}M/.....XMM$....MW.$MMMMMMMMMM`..@M.........RMMMMME..M.......WM.}MMMMMMM}.....YM!.....$MMMMMMMMMM,......
#  ....}M>.......MR..........1Mi.....XMME....M$.....`MX.......NM.......`MK.......%M.......$M.1Mi...........IM'.........:MF.........
#  ...MN.M@......MR.........M@.MM....XM,IM~..M$.....,MF.......NM......KM:........%M.......$M.1M+..........ME.M$........`M&.........
# ...MM.MM......MR.........MM.MM....XM,XM,..M$.....,MF.......NM......KM:........%M.......EM.1M>MMMMMMM....M%.MW........`M&.........
#  .lM>...}Mi....MR.......}Mi...1M/..XM'..ME.M$.....,MF.......NM......KM:........%MMMMMMMM$M.1M1:```....YM~...*M!......`M&.........
#  KWMEKRK$M$&...MR......#WMEKRK$M$K.XM'..>FKM$.....,MF.......NM......KM:........%M.......$M.1M+.......#%M#KRKWMEX.....`M&.........
#  M%.......M@...MR......MN.......MM.XM'...YMM$.....,MF.......NM.......:MK.......%M.......$M.1Mi.......M#.......MW.....`M&.........
#  MN.......MM...M#......M@.......MM.XM'.....MW.....,M&.......NM.........KMMMMM..NM.......$M.}MMMMMMM}.ME.......M%.....,M&.........
#  ................................................................................................................................
#  .......................................................................................................................By:huzpsb

#是否显示调试信息，如序列异常，vl等
debug: false
#AI服务器地址
server: "127.0.0.1"
#AI端口
port: 1451
#惩罚指令
cmd: "ban %p"
